>P1;query
sequence:query:   1: :  97: :: : 0.00: 0.00
TEPMAWNETADLGLDIGAQGEPLGYRQDDPSYRSFHSGGYGQDALGMDPMMEHEMGGHHPGADYPVDGLPDL--GHAQDLMDGLPPGDSNQLAWFDTDL*
>P1;d1c7ka_
structureX:d1c7ka_:  80:A: 111:A: : :-1.00:-1.00
-------------------------------------------------VTAHETG--------HVLGLPDHYQGPCSELMSGGGPGPS----------*
>P1;PoingAA
structureX:PoingAA:   1: :  97: :: : -1.00: -1.00
TEPMAWNETADLGLDIGAQGEPLGYRQDDPSYRSFHSGGYGQDALGMDPMMEHEMGGHHPGADYPVDGLPDL--GHAQDLMDGLPPGDSNQLAWFDTDL*
