>P1;query
sequence:query:   1: : 148: :: : 0.00: 0.00
MATQADLMELDMAMEPDRKAAVSHWQQQSYLDSGIHSGATTTAPSLSGKGNPEEEDVDTSQVLYEWEQGFSQSFTQEQVADIDGQYAMTRAQRVRAAMFP
ETLDEGMQIPSTQFDAAHPTNVQRLAEPSQMLKHAVVNLINYQDDAEL*
>P1;c2g57A_
structureX:c2g57A_:   19 :: 44 :: : :-1.00:-1.00
------------------KAAVSHWQQQSYLDSGIHSGATTTAP--------------------------------------------------------
-----------------------------------------------*
>P1;c4onsB_
structureX:c4onsB_:   83 :: 143 :: : :-1.00:-1.00
----------------------------------------------------------------------------------DGQYAMTRAQRVRAAMFP
ETLDEGMQIPSTQFDAAHPTNVQRLAEPSQMLKHAVVNLINYQ----*
>P1;PoingAA
structureX:PoingAA:  1: : 148: :: : 0.00: 0.00
MATQADLMELDMAMEPDRKAAVSHWQQQSYLDSGIHSGATTTAPSLSGKGNPEEEDVDTSQVLYEWEQGFSQSFTQEQVADIDGQYAMTRAQRVRAAMFP
ETLDEGMQIPSTQFDAAHPTNVQRLAEPSQMLKHAVVNLINYQDDAEL*
