>P1;query
sequence:query:   1: : 97: :: : 0.00: 0.00
TEPMAWNETADLGLDIGAQGEPLGYRQDDPSYRSFHSGGYGQDALGMDPMMEHEMGGHHPGADYPVDGLPDLGHAQDLMDGLPPGDSNQLAWFDTDL*
>P1;d1c7ka_
structureX:d1c7ka_:   50 :: 87 :: : :-1.00:-1.00
-------------------------------------------------MMEHEMGGHHPGADYPVDGLPDLGHAQDLMDGLPPGDS---------*
>P1;PoingAA
structureX:PoingAA:  1: : 97: :: : 0.00: 0.00
TEPMAWNETADLGLDIGAQGEPLGYRQDDPSYRSFHSGGYGQDALGMDPMMEHEMGGHHPGADYPVDGLPDLGHAQDLMDGLPPGDSNQLAWFDTDL*
